### ISSUE TITLE
Downloading images without showing them. 

### ISSUE THREAD

**Issue by ghost** [many-fac3d-g0d/ServeIt#2]
I have some images i want to browse from the the browser but it download it instead:

![Screenshot_20211022_115126](https://user-images.githubusercontent.com/88058138/138435695-08ed9ebc-479c-4341-9e18-fe2be65dca84.jpg)

The interface isn't that user friendly on both web and mobile.

For example, one should write path by its own. Adding a folder selector would be nice.

I does reset the port and the folder when i start it up...

The barcode is very big, you could adjust it.

Otherwise it is a great app ;)

Best Regards!

**Comment by many-fac3d-g0d** [comment]
@cloneconf Adding a file browser is already in my todo list - Didnt add this feature in the initial build becoz wanted it to b simple

Regarding the webpage, the design is deliberate to mimic other simple http servers, but will try to refresh the overall UI in the next update

**Comment by many-fac3d-g0d** [comment]
@cloneconf the barcode size has been reduced and tested in smaller devices and a directory picker has been added. And for browsing images from the web page - some browsers support this. Since this depends entirely on the browser used, nothing much can be done from the app end.
