### ISSUE TITLE
Cannot view non media files

### ISSUE THREAD

**Issue by absolutelynothinghere** [many-fac3d-g0d/ServeIt#4]
On Android 11 I can't give the app full storage permissions, only media. So when I start a server it only displays picture files and nothing else (no HTML files for example). Any fix for this?

**Comment by many-fac3d-g0d** [comment]
@absolutelynothinghere do u mean u want to serve a html page with ServeIt instead of just media files. If yes I think it needs some work, basically designed ServeIt for sharing of files between devices.

**Comment by ZiyaCu** [comment]
Hi @many-fac3d-g0d, I have the same issue on android 11. I checked app permissions and the options are "Storage permission: only media" and "no storage permission" (there is no "full storage permission" option), so the app can see media files like images and videos but not apk files, txt files etc. 
To solve it, you should edit the manifest file according to this page: https://developer.android.com/training/data-storage/manage-all-files

**Comment by many-fac3d-g0d** [comment]
Fixed in https://github.com/many-fac3d-g0d/ServeIt/pull/10

**Comment by many-fac3d-g0d** [comment]
Fix available on F-Droid [ServeIt v2.0.0 build](https://f-droid.org/repo/com.example.flutter_http_server_40.apk), pls download. Supports Android version > 11 and upload functionality to receive files via ServeIt.

**Comment by ZiyaCu** [comment]
I can't see v2.0.0 right now but I will check it tomorrow. Thanks!
