### ISSUE TITLE
cannot start server without wifi connection

### ISSUE THREAD

**Issue by adbenitez** [many-fac3d-g0d/ServeIt#5]
why is wifi connection needed? I just want to set an http server to test local html files / projects

**Comment by many-fac3d-g0d** [comment]
@adbenitez srry for the delayed response, basically we need some local network to bind to a ip:port url to serve files. So we would need some kind of wifi network for dis. Also It would b a security issue to bind to public ip:port address & in many cases public ip addresses are just NAT addresses and internally firewalled by ISPs

**Comment by adbenitez** [comment]
hi @many-fac3d-g0d, but as I said I was wanting to test local html files, if there is no wifi, I guess the app could listen in `localhost`/`127.0.0.1` that is listening only to local connections from the device itself, so I don't get the security issue the app would not be listening on `0.0.0.0` or any public accessible IP :thinking:

**Comment by many-fac3d-g0d** [comment]
Fixed in https://github.com/many-fac3d-g0d/ServeIt/pull/10

**Comment by many-fac3d-g0d** [comment]
Fix available on F-Droid [ServeIt v2.0.0 build](https://f-droid.org/repo/com.example.flutter_http_server_40.apk), pls download.

**Comment by adbenitez** [comment]
@many-fac3d-g0d thanks a lot!!! ❤️
