### ISSUE TITLE
Port number becomes invisible

### ISSUE THREAD

**Issue by niccokunzmann** [many-fac3d-g0d/ServeIt#6]
When I type in 800, I can see the port number.
When I type in 8000, it is not visible any more because it does not fit.

Possible solution:
Make the port number field bigger. Numbers like 60000 should fit in there.

![Screenshot_20220108-175122](https://user-images.githubusercontent.com/564768/154834368-b4b9ea87-9c41-4c6c-be6c-9d9305deda49.png)
![Screenshot_20220108-175126](https://user-images.githubusercontent.com/564768/154834363-e82cbb73-fdfe-4564-a6f3-b1cef2c810b0.png)

**Comment by many-fac3d-g0d** [comment]
@niccokunzmann srry for the delayed response. Thanks for reporting, This is a bug & I'm looking forward to revamp the UI altogether. But honestly this might take some time & I would welcome any contributions to the UI part from the community.

**Comment by many-fac3d-g0d** [comment]
Issue fixed in https://github.com/many-fac3d-g0d/ServeIt/pull/8

**Comment by niccokunzmann** [comment]
Uh nice! Thanks!
