### ISSUE TITLE
Allow working for localhost

### ISSUE THREAD

**Issue by sgued** [many-fac3d-g0d/ServeIt#9]
Hi, 

I'm trying to find an efficient way to browse a local folder on my phone that is the output of a statically generated website. Is there a way to make `ServeIt` work over localhost?

My goal is to be able to access the files through my web browser through `http://localhost/8080/`, and to reject on the other hand any incoming request from outside my phone.

**Comment by many-fac3d-g0d** [comment]
Fixed in https://github.com/many-fac3d-g0d/ServeIt/pull/10

**Comment by many-fac3d-g0d** [comment]
Fix available on F-Droid [ServeIt v2.0.0 build](https://f-droid.org/repo/com.example.flutter_http_server_40.apk), pls download. ServeIt should only bind to local network and with the new fix it can listen on 127.0.0.1 localhost.
